// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxyogdrxuxrqgoqlqkex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eW9nZHJ4dXhycWdvcWxxa2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTYwNDYsImV4cCI6MjA3MTQ5MjA0Nn0.xPsI3_zSZkcGLLVfWZZwCRpc7P1yTB7xxZYStJlVxUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});